version: '3.3'

services:
  proxy:
    restart: always
    image: nginx
    ports:
      - '3000:80'
    volumes:
      - ./proxy/config:/etc/nginx
      - ./proxy/certs:/etc/ssl/private
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 500M
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    env_file:
      - client/.env.production
  rest-api:
    stdin_open: true
    restart: always
    build:
      context: ./rest-api
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 500M
    env_file:
      - ./rest-api/.env
    environment:
      DATABASE_URL: 'mysql://root:root@mysql:3306/tickets'
  client:
    restart: always
    stdin_open: true
    build:
      context: ./client
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 500M
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
networks:
  default:
    external:
      name: mysqlnetwork
